// This file is auto-generated by @hey-api/openapi-ts

export type AttendeeCreate = {
    full_name: string;
    /**
     * Optional ID document number
     */
    document_id?: (string | null);
};

export type AttendeePublic = {
    full_name: string;
    /**
     * Optional ID document number
     */
    document_id?: (string | null);
    id: string;
    event_id: string;
    church_id: string;
    registered_by_email?: (string | null);
    church_name?: (string | null);
    event_name?: (string | null);
    created_at?: (string | null);
    checked_in_at?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BulkInviteCreateRequest = {
    invites: Array<ChurchInviteCreate>;
};

export type BulkInviteRequest = {
    invites: Array<ChurchInvite>;
};

export type ChurchCreate = {
    name: string;
};

export type ChurchesPublic = {
    data: Array<ChurchPublic>;
    count: number;
};

export type ChurchInvite = {
    church_id: string;
    quota: number;
};

export type ChurchInviteCreate = {
    name: string;
    quota: number;
};

export type ChurchPublic = {
    name: string;
    id: string;
};

export type EventCreate = {
    name: string;
    description?: (string | null);
    /**
     * Overall capacity of the event
     */
    total_quota?: number;
    start_date?: (string | null);
    end_date?: (string | null);
    /**
     * Deadline for registrations
     */
    max_registration_date?: (string | null);
    is_active?: boolean;
};

export type EventPublic = {
    name: string;
    description?: (string | null);
    /**
     * Overall capacity of the event
     */
    total_quota?: number;
    start_date?: (string | null);
    end_date?: (string | null);
    /**
     * Deadline for registrations
     */
    max_registration_date?: (string | null);
    is_active?: boolean;
    id: string;
};

export type EventStats = {
    event_name: string;
    total_quota: number;
    total_registered: number;
    checked_in_count: number;
    church_stats: Array<{
        [key: string]: unknown;
    }>;
};

export type EventUpdate = {
    name?: (string | null);
    description?: (string | null);
    total_quota?: (number | null);
    start_date?: (string | null);
    end_date?: (string | null);
    /**
     * Deadline for registrations
     */
    max_registration_date?: (string | null);
    is_active?: (boolean | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TokenGoogle = {
    token: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserBulkUpdate = {
    ids: Array<(string)>;
    role?: (UserRole | null);
    church_id?: (string | null);
    is_active?: (boolean | null);
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    is_google_account?: boolean;
    created_at?: string;
    password: string;
    church_id?: (string | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    is_google_account?: boolean;
    created_at?: string;
    id: string;
    church_id?: (string | null);
    church_name?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    church_id?: (string | null);
    recaptcha_token?: (string | null);
};

export type UserRole = 'ADMIN' | 'SUPERVISOR' | 'DIGITER' | 'USER';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: (UserRole | null);
    is_google_account?: boolean;
    created_at?: string;
    password?: (string | null);
    church_id?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    church_id?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type EventsCreateChurchData = {
    requestBody: ChurchCreate;
};

export type EventsCreateChurchResponse = (ChurchPublic);

export type EventsReadChurchesData = {
    limit?: number;
    skip?: number;
};

export type EventsReadChurchesResponse = (ChurchesPublic);

export type EventsCreateEventData = {
    requestBody: EventCreate;
};

export type EventsCreateEventResponse = (EventPublic);

export type EventsReadEventsData = {
    limit?: number;
    skip?: number;
};

export type EventsReadEventsResponse = (Array<EventPublic>);

export type EventsGetMyEventsResponse = (Array<EventPublic>);

export type EventsReadEventData = {
    eventId: string;
};

export type EventsReadEventResponse = (EventPublic);

export type EventsUpdateEventData = {
    eventId: string;
    requestBody: EventUpdate;
};

export type EventsUpdateEventResponse = (EventPublic);

export type EventsInviteChurchToEventData = {
    churchId: string;
    eventId: string;
    quota: number;
};

export type EventsInviteChurchToEventResponse = (EventPublic);

export type EventsGetEventChurchesData = {
    eventId: string;
};

export type EventsGetEventChurchesResponse = (ChurchesPublic);

export type EventsGetMyRegistrationCountData = {
    eventId: string;
};

export type EventsGetMyRegistrationCountResponse = (number);

export type EventsGetEventStatsData = {
    eventId: string;
};

export type EventsGetEventStatsResponse = (EventStats);

export type EventsGetEventAttendeesData = {
    eventId: string;
    limit?: number;
    skip?: number;
    q?: string;
};

export type EventsGetEventAttendeesResponse = (Array<AttendeePublic>);

export type EventsGetEventDigitersData = {
    eventId: string;
};

export type EventsGetEventDigitersResponse = (Array<UserPublic>);

export type EventsInviteChurchesBulkData = {
    eventId: string;
    requestBody: BulkInviteRequest;
};

export type EventsInviteChurchesBulkResponse = (unknown);

export type EventsInviteChurchesCreateBulkData = {
    eventId: string;
    requestBody: BulkInviteCreateRequest;
};

export type EventsInviteChurchesCreateBulkResponse = (unknown);

export type EventsRegisterAttendeeData = {
    eventId: string;
    requestBody: AttendeeCreate;
};

export type EventsRegisterAttendeeResponse = (AttendeePublic);

export type EventsSearchAttendeeByDocumentData = {
    documentId: string;
    eventId: string;
};

export type EventsSearchAttendeeByDocumentResponse = (AttendeePublic);

export type EventsSearchAttendeeByNameData = {
    eventId: string;
    limit?: number;
    q: string;
};

export type EventsSearchAttendeeByNameResponse = (Array<AttendeePublic>);

export type EventsDeleteAttendeeData = {
    attendeeId: string;
    eventId: string;
};

export type EventsDeleteAttendeeResponse = ({
    [key: string]: (string);
});

export type EventsGetEventDuplicatesData = {
    eventId: string;
};

export type EventsGetEventDuplicatesResponse = (Array<{
    [key: string]: unknown;
}>);

export type EventsCleanupEventDuplicatesData = {
    eventId: string;
};

export type EventsCleanupEventDuplicatesResponse = ({
    [key: string]: unknown;
});

export type EventsCheckinAttendeeData = {
    attendeeId: string;
    eventId: string;
};

export type EventsCheckinAttendeeResponse = (AttendeePublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginLoginGoogleData = {
    requestBody: TokenGoogle;
};

export type LoginLoginGoogleResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    role?: (UserRole | null);
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersUpdateUsersBulkData = {
    requestBody: UserBulkUpdate;
};

export type UsersUpdateUsersBulkResponse = (unknown);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);