"""Add max_registration_date to Event (Real)

Revision ID: 10e440160cdd
Revises: ce255cef109f
Create Date: 2026-01-09 13:46:02.212706

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '10e440160cdd'
down_revision = 'ce255cef109f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('max_registration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'max_registration_date')
    # ### end Alembic commands ###
