"""Add start_date and end_date to Event

Revision ID: 56161934db36
Revises: 930260c90ef5
Create Date: 2026-01-09 21:01:57.052659

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '56161934db36'
down_revision = '930260c90ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'end_date')
    op.drop_column('event', 'start_date')
    # ### end Alembic commands ###
