"""Add is_google_account to User

Revision ID: 5a52e89f5a3a
Revises: a82c7d9e1f2b
Create Date: 2026-01-10 01:41:39.352718

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5a52e89f5a3a'
down_revision = 'a82c7d9e1f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_google_account', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_google_account')
    # ### end Alembic commands ###
