"""Add Event Management Models and User Roles

Revision ID: 82407880bb2e
Revises: 1a31ce608336
Create Date: 2026-01-09 13:30:46.891047

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '82407880bb2e'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create Enum manually for Postgres
    from sqlalchemy.dialects import postgresql
    user_role = postgresql.ENUM('ADMIN', 'SUPERVISOR', 'DIGITER', name='userrole')
    user_role.create(op.get_bind(), checkfirst=True)

    op.create_table('church',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_church_name'), 'church', ['name'], unique=True)
    op.create_table('event',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('total_quota', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventchurchlink',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('church_id', sa.Uuid(), nullable=False),
    sa.Column('quota_limit', sa.Integer(), nullable=False),
    sa.Column('registered_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'church_id')
    )
    op.create_table('attendee',
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('church_id', sa.Uuid(), nullable=False),
    sa.Column('registered_by_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['church.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['registered_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('role', sa.Enum('ADMIN', 'SUPERVISOR', 'DIGITER', name='userrole'), nullable=False))
    op.add_column('user', sa.Column('church_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user', 'church', ['church_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'church_id')
    op.drop_column('user', 'role')
    
    # Drop Enum
    from sqlalchemy.dialects import postgresql
    user_role = postgresql.ENUM('ADMIN', 'SUPERVISOR', 'DIGITER', name='userrole')
    user_role.drop(op.get_bind(), checkfirst=True)

    op.drop_table('attendee')
    op.drop_table('eventchurchlink')
    op.drop_table('event')
    op.drop_index(op.f('ix_church_name'), table_name='church')
    op.drop_table('church')
    # ### end Alembic commands ###
