"""update_models_events_and_users

Revision ID: 930260c90ef5
Revises: 10e440160cdd
Create Date: 2026-01-09 14:07:40.004704

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '930260c90ef5'
down_revision = '10e440160cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
