"""Add max_registration_date to Event

Revision ID: ce255cef109f
Revises: 82407880bb2e
Create Date: 2026-01-09 13:44:57.644379

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ce255cef109f'
down_revision = '82407880bb2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
