"""Add checked_in_by to Attendee

Revision ID: ef9e6edec2c4
Revises: 75c34c4b4959
Create Date: 2026-01-30 14:24:12.541953

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ef9e6edec2c4'
down_revision = '75c34c4b4959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendee', sa.Column('checked_in_at', sa.DateTime(), nullable=True))
    op.add_column('attendee', sa.Column('checked_in_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'attendee', 'user', ['checked_in_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendee', type_='foreignkey')
    op.drop_column('attendee', 'checked_in_by_id')
    op.drop_column('attendee', 'checked_in_at')
    # ### end Alembic commands ###
