"""Add_created_at_to_Attendee

Revision ID: fcf040f55e24
Revises: 56161934db36
Create Date: 2026-01-09 22:06:14.360968

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fcf040f55e24'
down_revision = '56161934db36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendee', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendee', 'created_at')
    # ### end Alembic commands ###
